### ISSUE TITLE
Segmentation fault      $php_fpm_BIN --daemonize $php_opts

### ISSUE THREAD

**Issue by tianmingxing** [laruence/yaconf#26]
安装好扩展并开启扩展，重启fpm进程时遇到错误：

```
Starting php-fpm /etc/init.d/php-fpm7: line 53: 17443 Segmentation fault      $php_fpm_BIN --daemonize $php_opts
```

我使用php7.0.x，请帮助修复这个问题。

**Comment by laruence** [comment]
首先让他coredump出来, 然后把backtrace贴出来, 才好确定是哪里出了问题哈

**Comment by tianmingxing** [comment]
好的，我周一去公司了协调运维把这些打印出来。

**Comment by tianmingxing** [comment]
文件我传不上来，在这里。我放你的邮箱`laruence@php.net`

**Comment by tianmingxing** [comment]
我发你邮箱没有成功，你还有其它邮箱地址吗？

**Comment by laruence** [comment]
你不能直接给我发core文件啊(php邮件箱不能发附件), 你要在本地用gdb, 把backtrace打印出来就行了

**Comment by tianmingxing** [comment]
大神，我们公司运维也不知道如何打印出“backtrace”，现在core文件是生成了，能告知一下我们该如何帮你提供这个信息吗？

```
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Missing separate debuginfo for the main executable file
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/c4/93a5d1d7dfde8a8613a31d93c26d9626620140
[New Thread 3705]
Core was generated by `/usr/local/php7.0.18/bin/php -r var_dump(Yaconf::get(ad))'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f7cf096deee in ?? ()
"/usr/local/php7.0.18/bin/core.3705" is a core file.
Please specify an executable to debug.
(gdb) backtrace
#0  0x00007f7cf096deee in ?? ()
#1  0x000000000000000c in ?? ()
#2  0x0000000000000003 in ?? ()
#3  0x00007fff6a174f50 in ?? ()
#4  0x00007f7cf6a02000 in ?? ()
#5  0x00007fff6a174e58 in ?? ()
#6  0x00007fff6a174e40 in ?? ()
#7  0x0000000002b23bf0 in ?? ()
#8  0x0000000000000006 in ?? ()
#9  0x0000000001128920 in ?? ()
#10 0x00000000007d543c in ?? ()
#11 0x0000000000000020 in ?? ()
#12 0x00007fff6a175bac in ?? ()
#13 0x00007fff6a174f80 in ?? ()
#14 0x0000000000000006 in ?? ()
#15 0x0000000000000005 in ?? ()
#16 0x00007fff6a174f50 in ?? ()
#17 0x00007fff6a175ba0 in ?? ()
#18 0x00000000007d20dc in ?? ()
#19 0x00007fff6a1750e0 in ?? ()
#20 0x00007fff6a176040 in ?? ()
#21 0x00000110009515db in ?? ()
#22 0x00000000000000c8 in ?? ()
#23 0x00007fff6a174f20 in ?? ()
#24 0x00000000000000c7 in ?? ()
#25 0x00007fff6a175ba0 in ?? ()
#26 0x00000000f9ff8609 in ?? ()
#27 0x00007fff6a175d30 in ?? ()
#28 0x00007fff6a175db0 in ?? ()
#29 0x00007fff6a1750e0 in ?? ()
#30 0x00007fff6a175dc0 in ?? ()
#31 0x00007fff6a175dd8 in ?? ()
---Type <return> to continue, or q <return> to quit---
#32 0x00007fff6a175dd0 in ?? ()
#33 0xffffffffffffffff in ?? ()
#34 0x00007fff6a1750e0 in ?? ()
#35 0xffffffffffffffff in ?? ()
#36 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by laruence** [comment]
http://bugs.php.net/bugs-generating-backtrace.php

**Comment by tianmingxing** [comment]
我定位到问题了，yaconf.directory = "/config" #存放配置文件的目录
我在config下面创建了memory.ini文件和，结果就出现了上面的问题，移出后就好了。
所以是不是使用了关键字啊。。。

**Comment by laruence** [comment]
你的memory.ini文件张啥样

**Comment by tianmingxing** [comment]
memory.ini

```
;memcache服务地址
[memcache]
servers[host] = '10.xx.xxx.10'
servers[host] = '10.xx.xxx.12'
servers[port] = 9101
servers[weight] = 100
```

就上面这些比较简单吧

**Comment by laruence** [comment]
诶, 你试试改成  servers.host = '10.xx.xxxx.10'

**Comment by laruence** [comment]
好, 我知道问题了, 应该已经修复了! 谢谢报告

**Comment by tianmingxing** [comment]
我直接从master分支上下载源码，编译安装就可以了吧，那后续有问题我再向你反馈。

**Comment by laruence** [comment]
恩, 或者也可以从pecl下载, 我刚刚更新了一个版本
